#! /usr/bin/env python
# vim : set fileencoding=utf-8 expandtab noai ts=4 sw=4 filetype=python :
top = '..'

def build(self):
  self(
    name            = 'signalkit',
    export_includes = self.top_dir,
    uselib          = 'BOOST SYSTEMC',
    use             = 'common',
    install_path    = '${PREFIX}/lib',
  )
  self.install_files('${PREFIX}/include', self.path.ant_glob('**/*.h', excl=['**/tests/**', '**/extern/**', '**/contrib/**', '**/platform/**', '**/software/**', '**/.svn/**', '**/.git/**']), relative_trick=True)

