#! /usr/bin/env python
# vim : set fileencoding=utf-8 expandtab noai ts=4 sw=4 filetype=python :
top = '..'

def build(bld):
  bld(
    name            = 'signalkit',
    export_includes = '.',
    uselib          = 'BOOST SYSTEMC',
    use             = 'common',
    install_path    = '${PREFIX}/lib',
  )
  bld.install_files('${PREFIX}/include', bld.path.ant_glob('**/*.h', excl=['**/tests/**', '**/extern/**', '**/contrib/**', '**/platform/**', '**/software/**', '**/.svn/**', '**/.git/**']), relative_trick=True)

  bld(
    target       = 'signalkit.simple.test',
    features     = 'cxx cprogram test',
    source       = 'tests/simple.cpp',
    includes     = '.',
    uselib       = 'BOOST SYSTEMC',
    use          = 'signalkit common',
    install_path = None,
  )
  
  bld(
    target       = 'signalkit.systemc.test',
    features     = 'cxx cprogram test',
    source       = 'tests/systemc.cpp',
    includes     = '.',
    uselib       = 'BOOST SYSTEMC',
    use          = 'signalkit common',
    install_path = None,
  )
  
  bld(
    target       = 'signalkit.datatypemapping.test',
    features     = 'cxx cprogram test',
    source       = 'tests/datatypemapping.cpp',
    includes     = '.',
    uselib       = 'BOOST SYSTEMC',
    use          = 'signalkit common',
    install_path = None,
  )
   
