#! /usr/bin/env python
# encoding: utf-8
#*********************************************************************
# Copyright 2010, Institute of Computer and Network Engineering,
#                 TU-Braunschweig
# All rights reserved
# Any reproduction, use, distribution or disclosure of this program,
# without the express, prior written consent of the authors is 
# strictly prohibited.
#
# University of Technology Braunschweig
# Institute of Computer and Network Engineering
# Hans-Sommer-Str. 66
# 38118 Braunschweig, Germany
#
# ESA SPECIAL LICENSE
#
# This program may be freely used, copied, modified, and redistributed
# by the European Space Agency for the Agency's own requirements.
#
# The program is provided "as is", there is no warranty that
# the program is correct or suitable for any purpose,
# neither implicit nor explicit. The program and the information in it
# contained do not necessarily reflect the policy of the European 
# Space Agency or of TU-Braunschweig.
#*********************************************************************
# Title:      wscript
#
# ScssId:
#
# Origin:     HW-SW SystemC Co-Simulation SoC Validation Platform
#
# Purpose:    WAF build script for mmu_cache library.
#
# Method:     $ ./waf configure; ./waf # to build it on top level
#
# Modified on $Date$
#          at $Revision$
#          by $Author$
#
# Principal:  European Space Agency
# Author:     VLSI working group @ IDA @ TUBS
# Maintainer: Rolf Meyer
# Reviewed:
#*********************************************************************
top = '../..'

def build(bld):

  bld(
    target         = 'mmu_cache',
    features       = 'cxx cxxstlib',
    source         = [ 'lib/icio_payload_extension.cpp', 
                       'lib/dcio_payload_extension.cpp',
                       'lib/localram.cpp',
                       'lib/nocache.cpp',
                       'lib/vectorcache.cpp',
                       'lib/ivectorcache.cpp',
                       'lib/dvectorcache.cpp',
                       'lib/mmu.cpp', 
                       'lib/mmu_cache.cpp' ],
    export_includes = 'lib',
    uselib         = 'SYSTEMC TLM AMBA AMBAMEM GREENSOCS',
    use            = 'common utils',
    install_path   = '${PREFIX}/lib',
  )
