#! /usr/bin/env python
# encoding: utf-8
#*********************************************************************
# Copyright 2010, Institute of Computer and Network Engineering,
#                 TU-Braunschweig
# All rights reserved
# Any reproduction, use, distribution or disclosure of this program,
# without the express, prior written consent of the authors is 
# strictly prohibited.
#
# University of Technology Braunschweig
# Institute of Computer and Network Engineering
# Hans-Sommer-Str. 66
# 38118 Braunschweig, Germany
#
# ESA SPECIAL LICENSE
#
# This program may be freely used, copied, modified, and redistributed
# by the European Space Agency for the Agency's own requirements.
#
# The program is provided "as is", there is no warranty that
# the program is correct or suitable for any purpose,
# neither implicit nor explicit. The program and the information in it
# contained do not necessarily reflect the policy of the European 
# Space Agency or of TU-Braunschweig.
#*********************************************************************
# Title:      wscript
#
# ScssId:
#
# Origin:     HW-SW SystemC Co-Simulation SoC Validation Platform
#
# Purpose:    this file contains the build system for the mmu_cache
#             model and all its testbenches
#
# Method:     $ ./waf configure; ./waf # to build it on top level
#
# Modified on $Date$
#          at $Revision$
#          by $Author$
#
# Principal:  European Space Agency
# Author:     VLSI working group @ IDA @ TUBS
# Maintainer: Rolf Meyer
# Reviewed:
#*********************************************************************
top = '..'
vsim_conf = """
[Library]
modelsim = $GRLIB_TECH
grlib = $GRLIB_TECH/grlib
unisim = $GRLIB_TECH/unisim
dw02 = $GRLIB_TECH/dw02
synplify = $GRLIB_TECH/synplify
techmap = $GRLIB_TECH/techmap
spw = $GRLIB_TECH/spw
eth = $GRLIB_TECH/eth
opencores = $GRLIB_TECH/opencores
gaisler = $GRLIB_TECH/gaisler
esa = $GRLIB_TECH/esa
micron = $GRLIB_TECH/micron
vsys = $GRLIB_TECH/vsys
std = $MODEL_TECH/../std
ieee = $MODEL_TECH/../ieee
vital2000 = $MODEL_TECH/../vital2000
verilog = $MODEL_TECH/../verilog
std_developerskit = $MODEL_TECH/../std_developerskit
synopsys = $MODEL_TECH/../synopsys
work = %(path)s/%(target)s

[vcom]
VHDL93 = 1
Show_source = 1
Show_Warning1 = 0
Show_Warning5 = 0
Quiet = 1

[vlog]
Quiet = 1

[vsim]
VoptFlow = 0
Resolution = 1ps
UserTimeUnit = ns
RunLength = 100
IterationLimit = 5000
BreakOnAssertion = 3
DefaultRadix = symbolic
TranscriptFile = transcript.txt
PathSeparator = /
UnbufferedOutput = 0

[lmc]
libsm = $MODEL_TECH/libsm.sl
libhm = $MODEL_TECH/libhm.sl
"""

def options(ctx):
  from os import environ
  gso = ctx.get_option_group("--amba")
  gso.add_option("--ambaexamples", dest="amba_examples", help="Basedir of your AMBAKit Examples", default=environ.get("AMBA_EXAMPLES",""))

def configure(ctx):
  from waflib.Options import options
  import os.path
  amba_examples = ''
  if options.amba_examples and options.amba_examples != "":
    amba_examples = os.path.abspath(os.path.expanduser(os.path.expandvars(os.path.join(options.amba_examples, 'ahb_ct_timing'))))
  elif options.amba_home and options.amba_home != "":
    amba_examples = os.path.abspath(os.path.expanduser(os.path.expandvars(os.path.join(options.amba_home, 'examples', 'ahb_ct_timing'))))

  ctx.check_cxx(
    header_name  = 'ahb_simple_bus.h ahb_simple_slave.h',
    msg          = "Checking for AMBAKit Example Mem",
    mandatory    = True,
    uselib       = 'AMBAMEM AMBA GREENSOCS BOOST SYSC TLM2',
    uselib_store = 'AMBAMEM',
    includes     = amba_examples,
    fragment     = """
                   #ifdef DEBUG_AMBA
                   # define DUMP(name, msg) std::cout<<"@"<<sc_core::sc_time_stamp()<<" /"<<(unsigned)sc_core::sc_delta_count()<<" ("<<name  <<"): "<<msg<<std::endl
                   #else
                   # define DUMP(name, msg)
                   #endif

                   #include <ahb_simple_bus.h>
                   #include <ahb_simple_slave.h>
                   
                   int main(int argc, char *argv[]) {
                     return 0;
                   }
    """,
    execute      = False
  )
  
def build(bld):

  bld(
    target         = 'mmu_cache',
    features       = 'cxx cxxstlib',
    source         = [ 'lib/icio_payload_extension.cpp', 
                       'lib/dcio_payload_extension.cpp',
		       'lib/localram.cpp',
		       'lib/nocache.cpp',
		       'lib/vectorcache.cpp',
		       'lib/ivectorcache.cpp',
		       'lib/dvectorcache.cpp',
                       'lib/mmu.cpp', 
		       'lib/mmu_cache.cpp' ],
    export_includes = 'lib',
    uselib         = 'SYSC TLM2 AMBA AMBAMEM GREENSOCS',
    use            = 'common',
  )

  bld(
    target       = 'mmucache.test1',
    features     = 'cxx cprogram test',
    source       = ['test1/testbench.cpp',
                    'test1/sim_model/main.cpp'],
    includes     = '. ./lib ./test1',
    uselib       = 'SYSC TLM2 AMBA GREENSOCS',
    use          = 'mmu_cache common utils',
  )

  bld(
    features     = 'modelsim',
    target       = 'mmucache.test1_ref',
    name         = 'mmucache_test1_ref',
    source       = ['test1/sim_ref/typ_adapters.vhd',
                    'test1/sim_ref/mmu_cache_wrapper.vhd',
                    '../../common/verbose.cpp',
                    '../utils/grlibdevice.cpp',
                    '../utils/ahb_rtl_ct.cpp',
                    './lib/icio_payload_extension.cpp',
                    './lib/dcio_payload_extension.cpp',
                    '../utils/cpu_lt_rtl_adapter.cpp',
                    'test1/testbench.cpp',
                    'test1/sim_ref/main.cpp'],
    uselib       = 'AMBA GREENSOCS AMBAMEM',
    defines      = 'FUNCTIONTEST SCVAL=10 T1VAL=6 T2VAL=3 TVAL3=2 TVAL4=8 TESTLENGTH=1 DEBUGOUT=1',
    includes     = './ ./test1 ./test1/sim_ref ./lib ../utils ../../../signalkit ../../common',
    config       =  vsim_conf,
  )  

  bld(
    target       = 'mmucache.test2',
    features     = 'cxx cprogram test',
    source       = ['test2/testbench.cpp',
                    'test2/sim_model/main.cpp'],
    includes     = '. ./lib ./test2',
    uselib       = 'SYSC TLM2 AMBA GREENSOCS',
    use          = 'mmu_cache common utils',
  )

  bld(
    features     = 'modelsim',
    target       = 'mmucache.test2_ref',
    name         = 'mmucache_test2_ref',
    source       = ['test2/sim_ref/typ_adapters.vhd',
                    'test2/sim_ref/mmu_cache_wrapper.vhd',
                    '../../common/verbose.cpp',
                    '../utils/grlibdevice.cpp',
                    '../utils/ahb_rtl_ct.cpp',
                    './lib/icio_payload_extension.cpp',
                    './lib/dcio_payload_extension.cpp',
                    '../utils/cpu_lt_rtl_adapter.cpp',
                    'test2/testbench.cpp',
                    'test2/sim_ref/main.cpp'],
    uselib       = 'AMBA GREENSOCS AMBAMEM',
    defines      = 'FUNCTIONTEST SCVAL=10 T1VAL=6 T2VAL=3 TVAL3=2 TVAL4=8 TESTLENGTH=1 DEBUGOUT=1',
    includes     = './ ./test2 ./test2/sim_ref ./lib ../utils ../../../signalkit ../../common',
    config       =  vsim_conf,
  )    

