#! /usr/bin/env python
# encoding: utf-8

top = '..'

def build(bld):
	bld.exec_command('cd contrib/cult/build && cmake .. -DTARGET_ARCH=linux64 -DCULT_SUBLEVELS=10 -DSYSTEMC_VERSION=2.2 -DSYSTEMC_HOME=/opt/tools/systemc/ -DTLM_HOME=/opt/tools/systemc/include/tlm/ -DSYSTEMC_LIBRARY=/opt/tools/systemc/lib-linux64/ -DSYSTEMC_INCLUDE_DIR=/opt/tools/systemc/include/ -DSYSTEMCTLM2_INCLUDE_DIR=/opt/tools/systemc/include/tlm/ && make cult cult_sysc cult_tlm')
	


