#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os

def build(bld):
    bld.objects(
        target = 'modules',
        source = 'scireg.cpp',
        includes = '. ..',
        use = 'SYSTEMC',
        install_path = None
    )

    bld.install_files(os.path.join(bld.env.PREFIX, 'include', 'trap', 'modules', 'register'), 'scireg.h register_if.hpp register_abstraction.hpp register_field.hpp register_register.hpp register_alias.hpp register_bank.hpp')
