#! /usr/bin/env python
# vim : set fileencoding=utf-8 expandtab noai ts=4 sw=4 filetype=python :
top = '../..'

def build(bld):

  bld(
    target          = 'ahbin',
    features        = 'cxx cxxstlib',
    source          = 'ahbin.cpp',
    export_includes = self.top_dir,
    includes = self.top_dir,
    uselib          = 'SYSTEMC TLM AMBA GREENSOCS',
    use             = 'common utils',
    install_path    = '${PREFIX}/lib',
  )

