#! /usr/bin/env python
# vim : set fileencoding=utf-8 expandtab noai ts=4 sw=4 filetype=python :
top = '../..'

def build(self):
  self(
    target          = 'ahbprof',
    features        = 'cxx cxxstlib',
    source          = 'ahbprof.cpp', 
    export_includes = self.top_dir,
    includes        = self.top_dir,
    use             = 'common BOOST SYSTEMC TLM AMBA GREENSOCS',
    install_path    = '${PREFIX}/lib',
  )
