#! /usr/bin/env python
# vim : set fileencoding=utf-8 expandtab noai ts=4 sw=4 filetype=python :
top = '../..'

def build(self):
    self(
        target  = 'trap',
        features = 'cxx cxxstlib',
        source  = [
          'osEmulator/syscCallB.cpp',
          'ToolsIf.cpp',
          'elfloader/elfFrontend.cpp',
          'elfloader/execLoader.cpp',
          'profiler/profInfo.cpp',
          'utils/trap_utils.cpp',
          'debugger/GDBConnectionManager.cpp',
        ],
        export_includes = '. utils',
        includes = '. utils',
        uselib          = 'BOOST SYSTEMC TLM AMBA GREENSOCS',
        install_path    = '${PREFIX}/lib',
    )
