#! /usr/bin/env python
# vim : set fileencoding=utf-8 expandtab noai ts=4 sw=4 filetype=python :
top = '../..'

def build(bld):
  bld(
    target          = 'ahbout',
    features        = 'cxx cxxstlib',
    source          = 'ahbout.cpp', 
    export_includes = '.',
    uselib          = 'BOOST SYSTEMC TLM AMBA GREENSOCS',
    use             = 'utils signalkit common',
    install_path   = '${PREFIX}/lib',
  )
