#! /usr/bin/env python
# encoding: utf-8
#*********************************************************************
# Copyright 2010, Institute of Computer and Network Engineering,
#                 TU-Braunschweig
# All rights reserved
# Any reproduction, use, distribution or disclosure of this program,
# without the express, prior written consent of the authors is 
# strictly prohibited.
#
# University of Technology Braunschweig
# Institute of Computer and Network Engineering
# Hans-Sommer-Str. 66
# 38118 Braunschweig, Germany
#
# ESA SPECIAL LICENSE
#
# This program may be freely used, copied, modified, and redistributed
# by the European Space Agency for the Agency's own requirements.
#
# The program is provided "as is", there is no warranty that
# the program is correct or suitable for any purpose,
# neither implicit nor explicit. The program and the information in it
# contained do not necessarily reflect the policy of the European 
# Space Agency or of TU-Braunschweig.
#*********************************************************************
# Title:      wscript
#
# ScssId:
#
# Origin:     HW-SW SystemC Co-Simulation SoC Validation Platform
#
# Purpose:    this file contains the build system for global tests
#
# Method:     $ ./waf configure; ./waf # to build it on top level
#
# Modified on $Date: 2011-06-07 10:41:59 +0200 (Tue, 07 Jun 2011) $
#          at $Revision: 446 $
#          by $Author: HWSWSIM $
#
# Principal:  European Space Agency
# Author:     VLSI working group @ IDA @ TUBS
# Maintainer: Rolf Meyer
# Reviewed:
#*********************************************************************
top = '../..'

def build(bld):
  # AES.sparc
  bld(
     features     = 'c cprogram sparc',
     target       = 'aes.sparc',
     cflags       = '-static -g -O1 -lm -mno-fpu',
     linkflags    = '-static -g -O1 -lm -mno-fpu',
     source       = ['AES.c'],
  )

  bld(
      features    = 'systest',
      system      = 'singlecore.lt.platform',
      rom         = 'singlecore.lt.prom',
      ram         = 'aes.sparc',
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.at.platform',
      rom         = 'singlecore.at.prom',
      ram         = 'aes.sparc',
  )
  
  # bcnt.sparc
  bld(
     features     = 'c cprogram sparc',
     target       = 'bcnt.sparc',
     cflags       = '-static -g -O1 -lm -mno-fpu',
     linkflags    = '-static -g -O1 -lm -mno-fpu',
     source       = ['bcnt.c'],
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.lt.platform',
      rom         = 'singlecore.lt.prom',
      ram         = 'bcnt.sparc',
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.at.platform',
      rom         = 'singlecore.at.prom',
      ram         = 'bcnt.sparc',
  )

  # blit.sparc
  bld(
     features     = 'c cprogram sparc',
     target       = 'blit.sparc',
     cflags       = '-static -g -O1 -lm -mno-fpu',
     linkflags    = '-static -g -O1 -lm -mno-fpu',
     source       = ['blit.c'],
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.lt.platform',
      rom         = 'singlecore.lt.prom',
      ram         = 'blit.sparc',
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.at.platform',
      rom         = 'singlecore.at.prom',
      ram         = 'blit.sparc',
  )

  # crc.sparc
  bld(
     features     = 'c cprogram sparc',
     target       = 'crc.sparc',
     cflags       = '-static -g -O1 -lm -mno-fpu',
     linkflags    = '-static -g -O1 -lm -mno-fpu',
     source       = ['crc.c'],
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.lt.platform',
      rom         = 'singlecore.lt.prom',
      ram         = 'crc.sparc',
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.at.platform',
      rom         = 'singlecore.at.prom',
      ram         = 'crc.sparc',
  )

  # des.sparc
  bld(
     features     = 'c cprogram sparc',
     target       = 'des.sparc',
     cflags       = '-static -g -O1 -lm -mno-fpu',
     linkflags    = '-static -g -O1 -lm -mno-fpu',
     source       = ['des.c'],
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.lt.platform',
      rom         = 'singlecore.lt.prom',
      ram         = 'des.sparc',
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.at.platform',
      rom         = 'singlecore.at.prom',
      ram         = 'des.sparc',
  )

  # dhry.sparc
  bld(
     features     = 'c cprogram sparc',
     target       = 'dhry.sparc',
     cflags       = '-static -g -O1 -lm -mno-fpu',
     linkflags    = '-static -g -O1 -lm -mno-fpu',
     source       = ['dhry.c'],
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.lt.platform',
      rom         = 'singlecore.lt.prom',
      ram         = 'dhry.sparc',
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.at.platform',
      rom         = 'singlecore.at.prom',
      ram         = 'dhry.sparc',
  )

  # engine.sparc
  bld(
     features     = 'c cprogram sparc',
     target       = 'engine.sparc',
     cflags       = '-static -g -O1 -lm -mno-fpu',
     linkflags    = '-static -g -O1 -lm -mno-fpu',
     source       = ['engine.c'],
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.lt.platform',
      rom         = 'singlecore.lt.prom',
      ram         = 'engine.sparc',
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.at.platform',
      rom         = 'singlecore.at.prom',
      ram         = 'engine.sparc',
  )

  # fft.sparc
  bld(
     features     = 'c cprogram sparc',
     target       = 'fft.sparc',
     cflags       = '-static -g -O1 -lm -mno-fpu',
     linkflags    = '-static -g -O1 -lm -mno-fpu',
     source       = ['fft.c'],
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.lt.platform',
      rom         = 'singlecore.lt.prom',
      ram         = 'fft.sparc',
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.at.platform',
      rom         = 'singlecore.at.prom',
      ram         = 'fft.sparc',
  )

  # fib.sparc
  bld(
     features     = 'c cprogram sparc',
     target       = 'fib.sparc',
     cflags       = '-static -g -O1 -lm -mno-fpu',
     linkflags    = '-static -g -O1 -lm -mno-fpu',
     source       = ['fib.c'],
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.lt.platform',
      rom         = 'singlecore.lt.prom',
      ram         = 'fib.sparc',
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.at.platform',
      rom         = 'singlecore.at.prom',
      ram         = 'fib.sparc',
  )

  # fir2.sparc
  bld(
     features     = 'c cprogram sparc',
     target       = 'fir2.sparc',
     cflags       = '-static -g -O1 -lm -mno-fpu',
     linkflags    = '-static -g -O1 -lm -mno-fpu',
     source       = ['fir2.c'],
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.lt.platform',
      rom         = 'singlecore.lt.prom',
      ram         = 'fir2.sparc',
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.at.platform',
      rom         = 'singlecore.at.prom',
      ram         = 'fir2.sparc',
  )

  # gamma.sparc
  bld(
     features     = 'c cprogram sparc',
     target       = 'gamma.sparc',
     cflags       = '-static -g -O1 -lm -mno-fpu',
     linkflags    = '-static -g -O1 -lm -mno-fpu',
     source       = ['gamma.c'],
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.lt.platform',
      rom         = 'singlecore.lt.prom',
      ram         = 'gamma.sparc',
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.at.platform',
      rom         = 'singlecore.at.prom',
      ram         = 'gamma.sparc',
  )

  # hanoi.sparc
  bld(
     features     = 'c cprogram sparc',
     target       = 'hanoi.sparc',
     cflags       = '-static -g -O1 -lm -mno-fpu',
     linkflags    = '-static -g -O1 -lm -mno-fpu',
     source       = ['hanoi.c'],
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.lt.platform',
      rom         = 'singlecore.lt.prom',
      ram         = 'hanoi.sparc',
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.at.platform',
      rom         = 'singlecore.at.prom',
      ram         = 'hanoi.sparc',
  )

  # heapsort.sparc
  bld(
     features     = 'c cprogram sparc',
     target       = 'heapsort.sparc',
     cflags       = '-static -g -O1 -lm -mno-fpu',
     linkflags    = '-static -g -O1 -lm -mno-fpu',
     source       = ['heapsort.c'],
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.lt.platform',
      rom         = 'singlecore.lt.prom',
      ram         = 'heapsort.sparc',
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.at.platform',
      rom         = 'singlecore.at.prom',
      ram         = 'heapsort.sparc',
  )

  # jpeg.sparc
  bld(
     features     = 'c cprogram sparc',
     target       = 'jpeg.sparc',
     cflags       = '-static -g -O1 -lm -mno-fpu',
     linkflags    = '-static -g -O1 -lm -mno-fpu',
     source       = ['jpeg.c'],
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.lt.platform',
      rom         = 'singlecore.lt.prom',
      ram         = 'jpeg.sparc',
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.at.platform',
      rom         = 'singlecore.at.prom',
      ram         = 'jpeg.sparc',
  )

  # lms.sparc
  bld(
     features     = 'c cprogram sparc',
     target       = 'lms.sparc',
     cflags       = '-static -g -O1 -lm -mno-fpu',
     linkflags    = '-static -g -O1 -lm -mno-fpu',
     source       = ['lms.c'],
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.lt.platform',
      rom         = 'singlecore.lt.prom',
      ram         = 'lms.sparc',
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.at.platform',
      rom         = 'singlecore.at.prom',
      ram         = 'lms.sparc',
  )

  # matrix.sparc
  bld(
     features     = 'c cprogram sparc',
     target       = 'matrix.sparc',
     cflags       = '-static -g -O1 -lm -mno-fpu',
     linkflags    = '-static -g -O1 -lm -mno-fpu',
     source       = ['matrix.c'],
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.lt.platform',
      rom         = 'singlecore.lt.prom',
      ram         = 'matrix.sparc',
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.at.platform',
      rom         = 'singlecore.at.prom',
      ram         = 'matrix.sparc',
  )

  # mdrall.sparc
  bld(
     features     = 'c cprogram sparc',
     target       = 'mdrall.sparc',
     cflags       = '-static -g -O1 -lm -mno-fpu',
     linkflags    = '-static -g -O1 -lm -mno-fpu',
     source       = ['mdrAll.c'],
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.lt.platform',
      rom         = 'singlecore.lt.prom',
      ram         = 'mdrall.sparc',
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.at.platform',
      rom         = 'singlecore.at.prom',
      ram         = 'mdrall.sparc',
  )

  # pocsag.sparc
  bld(
     features     = 'c cprogram sparc',
     target       = 'pocsag.sparc',
     cflags       = '-static -g -O1 -lm -mno-fpu',
     linkflags    = '-static -g -O1 -lm -mno-fpu',
     source       = ['pocsag.c'],
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.lt.platform',
      rom         = 'singlecore.lt.prom',
      ram         = 'pocsag.sparc',
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.at.platform',
      rom         = 'singlecore.at.prom',
      ram         = 'pocsag.sparc',
  )

  # queens.sparc
  bld(
     features     = 'c cprogram sparc',
     target       = 'queens.sparc',
     cflags       = '-static -g -O1 -lm -mno-fpu',
     linkflags    = '-static -g -O1 -lm -mno-fpu',
     source       = ['queens.c'],
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.lt.platform',
      rom         = 'singlecore.lt.prom',
      ram         = 'queens.sparc',
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.at.platform',
      rom         = 'singlecore.at.prom',
      ram         = 'queens.sparc',
  )

  # quicksort.sparc
  bld(
     features     = 'c cprogram sparc',
     target       = 'quicksort.sparc',
     cflags       = '-static -g -O1 -lm -mno-fpu',
     linkflags    = '-static -g -O1 -lm -mno-fpu',
     source       = ['quicksort.c'],
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.lt.platform',
      rom         = 'singlecore.lt.prom',
      ram         = 'quicksort.sparc',
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.at.platform',
      rom         = 'singlecore.at.prom',
      ram         = 'quicksort.sparc',
  )

  # tolstoy.sparc
  bld(
     features     = 'c cprogram sparc',
     target       = 'tolstoy.sparc',
     cflags       = '-static -g -O1 -lm -mno-fpu',
     linkflags    = '-static -g -O1 -lm -mno-fpu',
     source       = ['tolstoy.c'],
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.lt.platform',
      rom         = 'singlecore.lt.prom',
      ram         = 'tolstoy.sparc',
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.at.platform',
      rom         = 'singlecore.at.prom',
      ram         = 'tolstoy.sparc',
  )

  # v42.sparc
  bld(
     features     = 'c cprogram sparc',
     target       = 'v42.sparc',
     cflags       = '-static -g -O1 -lm -mno-fpu',
     linkflags    = '-static -g -O1 -lm -mno-fpu',
     source       = ['v42.c'],
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.lt.platform',
      rom         = 'singlecore.lt.prom',
      ram         = 'v42.sparc',
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.at.platform',
      rom         = 'singlecore.at.prom',
      ram         = 'v42.sparc',
  )

  # wavelt.sparc
  bld(
     features     = 'c cprogram sparc',
     target       = 'wavelt.sparc',
     cflags       = '-static -g -O1 -lm -mno-fpu',
     linkflags    = '-static -g -O1 -lm -mno-fpu',
     source       = ['wavelt.c'],
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.lt.platform',
      rom         = 'singlecore.lt.prom',
      ram         = 'wavelt.sparc',
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.at.platform',
      rom         = 'singlecore.at.prom',
      ram         = 'wavelt.sparc',
  )

  # whets.sparc
  bld(
     features     = 'c cprogram sparc',
     target       = 'whets.sparc',
     cflags       = '-static -g -O1 -lm -mno-fpu',
     linkflags    = '-static -g -O1 -lm -mno-fpu',
     source       = ['whets.c'],
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.lt.platform',
      rom         = 'singlecore.lt.prom',
      ram         = 'whets.sparc',
  )
  
  bld(
      features    = 'systest',
      system      = 'singlecore.at.platform',
      rom         = 'singlecore.at.prom',
      ram         = 'whets.sparc',
  )

