#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os

def build(bld):
    bld.objects(
        target = 'common',
        cxxflags = '-std=c++11',
        source = 'report.cpp',
        includes = '. ..',
        install_path = None
    )

    bld.install_files(os.path.join(bld.env.PREFIX, 'include', 'trap', 'common'), 'report.hpp tools_if.hpp')
