#! /usr/bin/env python
# vim : set fileencoding=utf-8 expandtab noai ts=4 sw=4 filetype=python :
top = '../..'

def build(bld):
  import os.path
  bld(
    target          = 'mctrl',
    features        = 'cxx cxxstlib',
    source          = 'mctrl.cpp', 
    export_includes = '.',
    uselib          = 'BOOST_PROGRAM_OPTIONS SYSTEMC TLM AMBA GREENSOCS',
    use             = 'memory utils signalkit common',
    install_path   = '${PREFIX}/lib',
  )
