#! /usr/bin/env python
# encoding: utf-8
#*********************************************************************
# Copyright 2010, Institute of Computer and Network Engineering,
#                 TU-Braunschweig
# All rights reserved
# Any reproduction, use, distribution or disclosure of this program,
# without the express, prior written consent of the authors is 
# strictly prohibited.
#
# University of Technology Braunschweig
# Institute of Computer and Network Engineering
# Hans-Sommer-Str. 66
# 38118 Braunschweig, Germany
#
# ESA SPECIAL LICENSE
#
# This program may be freely used, copied, modified, and redistributed
# by the European Space Agency for the Agency's own requirements.
#
# The program is provided "as is", there is no warranty that
# the program is correct or suitable for any purpose,
# neither implicit nor explicit. The program and the information in it
# contained do not necessarily reflect the policy of the European 
# Space Agency or of TU-Braunschweig.
#*********************************************************************
# Title:      wscript
#
# ScssId:
#
# Origin:     HW-SW SystemC Co-Simulation SoC Validation Platform
#
# Purpose:    this file contains the build system for the memory
#             controler tlm model and all its testbenches
#
# Method:     $ ./waf configure; ./waf # to build it on top level
#
# Modified on $Date$
#          at $Revision$
#          by $Author$
#
# Principal:  European Space Agency
# Author:     VLSI working group @ IDA @ TUBS
# Maintainer: Rolf Meyer
# Reviewed:
#*********************************************************************
top = '..'
vsim_conf = """
[Library]
modelsim = $GRLIB_TECH
grlib = $GRLIB_TECH/grlib
unisim = $GRLIB_TECH/unisim
dw02 = $GRLIB_TECH/dw02
synplify = $GRLIB_TECH/synplify
techmap = $GRLIB_TECH/techmap
spw = $GRLIB_TECH/spw
eth = $GRLIB_TECH/eth
opencores = $GRLIB_TECH/opencores
gaisler = $GRLIB_TECH/gaisler
esa = $GRLIB_TECH/esa
micron = $GRLIB_TECH/micron
vsys = $GRLIB_TECH/vsys
std = $MODEL_TECH/../std
ieee = $MODEL_TECH/../ieee
vital2000 = $MODEL_TECH/../vital2000
verilog = $MODEL_TECH/../verilog
std_developerskit = $MODEL_TECH/../std_developerskit
synopsys = $MODEL_TECH/../synopsys
work = %(path)s/%(target)s

[vcom]
VHDL93 = 1
Show_source = 1
Show_Warning1 = 0
Show_Warning5 = 0
Quiet = 1

[vlog]
Quiet = 1

[vsim]
VoptFlow = 0
Resolution = 1ps
UserTimeUnit = ns
RunLength = 100
IterationLimit = 5000
BreakOnAssertion = 3
DefaultRadix = symbolic
TranscriptFile = transcript.txt
PathSeparator = /
UnbufferedOutput = 0

[lmc]
libsm = $MODEL_TECH/libsm.sl
libhm = $MODEL_TECH/libhm.sl
"""

def options(ctx): 
  pass

def configure(ctx):
  ctx.env["VCOMFLAGS"] += ["-87", "-explicit"]

def build(bld):
  import os.path
  bld(
    target          = 'mctrl',
    features        = 'cxx cxxstlib',
    source          = 'mctrl.cpp', 
    export_includes = '.',
    uselib          = 'BOOST SYSC TLM2 AMBA GREENSOCS',
    use             = 'utils signalkit common'
  )

  bld(
    features     = 'cxx cprogram test',
    target       = 'mctrl.1.tlm.test',
    source       = ['test/test1/testbench.cpp',
                    'test/test1/top_tlm.cpp'],
    includes     = './ test test/test1',
    uselib       = 'BOOST SYSC TLM2 AMBA GREENSOCS',
    use          = 'mctrl utils signalkit common'
  )

  bld(
    features     = 'modelsim test',
    target       = 'mctrl.1.rtl.test',
    source       = [os.path.relpath(os.path.join(bld.env['GRLIB_HOME'], 'lib/contrib/sram32.vhd'), bld.path.get_src().abspath()),
                    '../../common/verbose.cpp',
                    'test/test1/testbench.cpp',
                    'test/test1/top_rtl.cpp'],
    uselib       = 'AMBA GREENSOCS AMBAMEM',
    defines      = 'TESTLENGTH=1',
    includes     = '. test ../utils ../../signalkit ../../common',
    config       =  vsim_conf,
  )  

  bld(
    features     = 'modelsim',
    target       = 'mctrl.test001.cosim.rtlahb',
    source       = [os.path.relpath(os.path.join(bld.env['GRLIB_HOME'], 'lib/contrib/sram32.vhd'), bld.path.get_src().abspath()),
                    os.path.relpath(os.path.join(bld.env['GRLIB_HOME'], 'lib/contrib/amba/ahbctrl.vhd'), bld.path.get_src().abspath()),
                    '../../common/verbose.cpp',
                    './test/conf001/mctrl_tb.cpp',
                    './test/conf001/cosim/mctrl_top_rtl_bus.cpp'],
    uselib       = 'AMBA GREENSOCS AMBAMEM',
    defines      = 'FUNCTIONTEST SCVAL=10 T1VAL=6 T2VAL=3 TVAL3=2 TVAL4=8 TESTLENGTH=1 DEBUGOUT=1',
    includes     = './ ./test ../utils ../../signalkit ../../common',
    config       =  vsim_conf,
  )  

  bld(
    features     = 'modelsim',
    target       = 'mctrl.test004.cosim.rtlahb',
    source       = ['../utils/sram16.vhd',
                    os.path.relpath(os.path.join(bld.env['GRLIB_HOME'], 'lib/contrib/amba/ahbctrl.vhd'), bld.path.get_src().abspath()),
                    '../../common/verbose.cpp',
                    './test/conf004/mctrl_tb.cpp',
                    './test/conf004/cosim/mctrl_top_rtl_bus.cpp'],
    uselib       = 'AMBA GREENSOCS AMBAMEM',
    defines      = 'FUNCTIONTEST SCVAL=10 T1VAL=6 T2VAL=3 TVAL3=2 TVAL4=8 TESTLENGTH=1 DEBUGOUT=1',
    includes     = './ ./test ../utils ../../signalkit ../../common',
    config       =  vsim_conf,
  )  

