#! /usr/bin/env python
# encoding: utf-8
#*********************************************************************
# Copyright 2010, Institute of Computer and Network Engineering,
#                 TU-Braunschweig
# All rights reserved
# Any reproduction, use, distribution or disclosure of this program,
# without the express, prior written consent of the authors is 
# strictly prohibited.
#
# University of Technology Braunschweig
# Institute of Computer and Network Engineering
# Hans-Sommer-Str. 66
# 38118 Braunschweig, Germany
#
# ESA SPECIAL LICENSE
#
# This program may be freely used, copied, modified, and redistributed
# by the European Space Agency for the Agency's own requirements.
#
# The program is provided "as is", there is no warranty that
# the program is correct or suitable for any purpose,
# neither implicit nor explicit. The program and the information in it
# contained do not necessarily reflect the policy of the European 
# Space Agency or of TU-Braunschweig.
#*********************************************************************
# Title:      wscript
#
# ScssId:
#
# Origin:     HW-SW SystemC Co-Simulation SoC Validation Platform
#
# Purpose:    this file contains the build system for the memory
#             controler tlm model and all its testbenches
#
# Method:     $ ./waf configure; ./waf # to build it on top level
#
# Modified on $Date: 2011-05-19 18:31:12 +0200 (Thu, 19 May 2011) $
#          at $Revision: 429 $
#          by $Author: HWSWSIM $
#
# Principal:  European Space Agency
# Author:     VLSI working group @ IDA @ TUBS
# Maintainer: Rolf Meyer
# Reviewed:
#*********************************************************************
top = '../..'
vsim_conf = """
[Library]
modelsim = $GRLIB_TECH
grlib = $GRLIB_TECH/grlib
unisim = $GRLIB_TECH/unisim
dw02 = $GRLIB_TECH/dw02
synplify = $GRLIB_TECH/synplify
techmap = $GRLIB_TECH/techmap
spw = $GRLIB_TECH/spw
eth = $GRLIB_TECH/eth
opencores = $GRLIB_TECH/opencores
gaisler = $GRLIB_TECH/gaisler
esa = $GRLIB_TECH/esa
micron = $GRLIB_TECH/micron
vsys = $GRLIB_TECH/vsys
std = $MODEL_TECH/../std
ieee = $MODEL_TECH/../ieee
vital2000 = $MODEL_TECH/../vital2000
verilog = $MODEL_TECH/../verilog
std_developerskit = $MODEL_TECH/../std_developerskit
synopsys = $MODEL_TECH/../synopsys
work = %(path)s/%(target)s

[vcom]
VHDL93 = 1
Show_source = 1
Show_Warning1 = 0
Show_Warning5 = 0
Quiet = 1

[vlog]
Quiet = 1

[vsim]
VoptFlow = 0
Resolution = 1ps
UserTimeUnit = ns
RunLength = 100
IterationLimit = 5000
BreakOnAssertion = 3
DefaultRadix = symbolic
TranscriptFile = %(path)s/%(target)s.transcript.txt
PathSeparator = /
UnbufferedOutput = 0

[lmc]
libsm = $MODEL_TECH/libsm.sl
libhm = $MODEL_TECH/libhm.sl
"""

def options(ctx): 
  pass

def configure(ctx):
  ctx.env["VCOMFLAGS"] += ["-87", "-explicit"]

def build(bld):
  import os.path
  bld(
    target          = 'mctrl',
    features        = 'cxx cxxstlib',
    source          = 'mctrl.cpp genericmemory.cpp ./tests/mctrl_test.cpp', 
    export_includes = '.',
    uselib          = 'BOOST_PROGRAM_OPTIONS SYSTEMC TLM AMBA GREENSOCS',
    use             = 'utils signalkit common'
  )

  bld(
    features     = 'cxx cprogram test',
    target       = 'mctrl.1.lt.test',
    source       = ['tests/test1/testbench.cpp',
                    'tests/test1/top_lt.cpp'],
    includes     = '. tests tests/test1 ../ahbctrl/tests',
    uselib       = 'BOOST_PROGRAM_OPTIONS SYSTEMC TLM AMBA GREENSOCS',
    use          = 'mctrl utils signalkit common'
  )

  bld(
    features     = 'cxx cprogram test',
    target       = 'mctrl.1.at.test',
    source       = ['tests/test1/testbench.cpp',
                    'tests/test1/top_at.cpp'],
    includes     = '. tests tests/test1 ../ahbctrl/tests',
    uselib       = 'BOOST_PROGRAM_OPTIONS SYSTEMC TLM AMBA GREENSOCS',
    use          = 'mctrl utils signalkit common'
  )

  bld(
    features     = 'cxx cprogram test',
    target       = 'mctrl.2.tlm.test',
    source       = ['tests/test2/testbench.cpp',
                    'tests/test2/top_tlm.cpp'],
    includes     = '. tests tests/test2 ../ahbctrl/tests',
    uselib       = 'BOOST_PROGRAM_OPTIONS SYSTEMC TLM AMBA GREENSOCS',
    use          = 'mctrl utils signalkit common'
  )
  
  bld(
    features     = 'cxx cprogram test',
    target       = 'mctrl.3.tlm.test',
    source       = ['tests/test3/testbench.cpp',
                    'tests/test3/top_tlm.cpp'],
    includes     = '. tests tests/test3 ../ahbctrl/tests',
    uselib       = 'BOOST_PROGRAM_OPTIONS SYSTEMC TLM AMBA GREENSOCS',
    use          = 'mctrl utils signalkit common'
  )
  
  bld(
    features     = 'cxx cprogram test',
    target       = 'mctrl.4.tlm.test',
    source       = ['tests/test4/testbench.cpp',
                    'tests/test4/top_tlm.cpp'],
    includes     = '. tests tests/test4 ../ahbctrl/tests',
    uselib       = 'BOOST_PROGRAM_OPTIONS SYSTEMC TLM AMBA GREENSOCS',
    use          = 'mctrl utils signalkit common'
  )

  bld(
    features     = 'cxx cprogram test',
    target       = 'mctrl.5.lt.test',
    source       = ['tests/test5/testbench.cpp',
                    'tests/test5/top_lt.cpp',
                    '../ahbctrl/tests/ahbctrl_test.cpp'],
    includes     = '. tests tests/test5 ../ahbctrl/tests',
    uselib       = 'BOOST_PROGRAM_OPTIONS SYSTEMC TLM AMBA GREENSOCS',
    use          = 'mctrl gptimer ahbctrl apbctrl utils signalkit common'
  )

  bld(
    features     = 'cxx cprogram test',
    target       = 'mctrl.5.at.test',
    source       = ['tests/test5/testbench.cpp',
                    'tests/test5/top_at.cpp',
                    '../ahbctrl/tests/ahbctrl_test.cpp'],
    includes     = '. tests tests/test5 ../ahbctrl/tests',
    uselib       = 'BOOST_PROGRAM_OPTIONS SYSTEMC TLM AMBA GREENSOCS',
    use          = 'mctrl gptimer ahbctrl apbctrl utils signalkit common'
  )

  #prom5  = bld(rule='cp ${SRC} ${TGT}', source='./tests/test5/prom.srec', target='prom.srec')
  #sram5  = bld(rule='cp ${SRC} ${TGT}', source='./tests/test5/sram.srec', target='sram.srec')
  #sdram5 = bld(rule='cp ${SRC} ${TGT}', source='./tests/test5/sdram.srec', target='sdram.srec')

  test5 = bld(
    features     = 'modelsim',
    target       = 'mctrl.5.rtl.test',
    name         = 'mctrl.5.rtl.test',
    source       = ['./tests/test5/config.vhd',
                    './tests/typ_adapters.vhd',
                    './tests/test5/mctrl_wrapper.vhd',
                    '../../common/verbose.cpp',
                    '../../common/timingmonitor.cpp',
                    '../utils/power_monitor.cpp',
                    '../utils/clkdevice.cpp',
                    '../utils/ahbdevice.cpp',
                    '../utils/apbdevice.cpp',
                    '../ahbctrl/adapters/ahbpipe.cpp',
                    '../ahbctrl/adapters/ahb_tlmbus_rtlslave_transactor.cpp',
                    '../ahbctrl/adapters/apb_tlmbus_rtlslave_transactor.cpp',
                    '../ahbctrl/tests/ahbctrl_test.cpp',
                    '../ahbctrl/ahbctrl.cpp',
                    '../apbctrl/apbctrl.cpp',
                    './tests/test5/testbench.cpp',
                    './tests/test5/top_rtl.cpp'],
    uselib        = 'AMBA GREENSOCS',
    includes      = './ ./tests ./tests/test5 ./test1/sim_rtl ./lib ../utils ../../signalkit ../../common ../ahbctrl ../ahbctrl/tests ../apbctrl ../ahbctrl/adapters',
    config        = vsim_conf,
  )

  
  #bld.add_manual_dependency(bld.path.find_node('mctrl.5.rtl.test'),bld.path.find_node('prom.srec'))
  #bld.add_manual_dependency(bld.path.find_node('mctrl.5.rtl.test'),bld.path.find_node('sram.srec'))
  #bld.add_manual_dependency(bld.path.find_node('mctrl.5.rtl.test'),bld.path.find_node('sdram.srec'))
