#! /usr/bin/env python
# vim : set fileencoding=utf-8 expandtab noai ts=4 sw=4 filetype=python :
top = '../..'

def build(self):
    self(
        target  = 'trap',
        features = 'cxx cxxstlib',
        source  = [
          #'osEmulator/syscCallB.cpp',
          'ToolsIf.cpp',
          #'elfloader/elfFrontend.cpp',
          #'elfloader/execLoader.cpp',
          'profiler/profInfo.cpp',
          'utils/trap_utils.cpp',
          'debugger/GDBConnectionManager.cpp',
        ],
        export_includes = ['.','utils',self.top_dir],
        includes        = ['.','utils',self.top_dir],
        use             = 'BOOST SYSTEMC TLM AMBA GREENSOCS ELF_LIB',
        install_path    = '${PREFIX}/lib',
    )
