#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os

REPOSITORY_PATH = 'core/trapgen'
REPOSITORY_NAME = 'TrapGen Runtime'
REPOSITORY_DESC = 'TrapGen Runtime branch'
REPOSITORY_TOOLS = [
]

def build(bld):
    if not hasattr(bld, "repository_root"):
        if bld.env['LICENSE'] == 'gpl':
            bld.recurse(os.path.join('libbfd', 'elfloader'))
        else:
            bld.recurse(os.path.join('libelf', 'elfloader'))

        bld.recurse('common debugger modules osemu profiler')

        bld.install_files(os.path.join(bld.env.PREFIX, 'include', 'trap'), 'trap.hpp')

    else:
        bld(
            target   = 'trap',
            features = 'cxx cxxstlib',
            #cxxflags = '-std=gnu++11',
            source   = [
                        'osemu/osemu_base.cpp',
                        'profiler/profiler_elements.cpp',
                        'common/report.cpp',
                        'modules/register/scireg.cpp',
                        'debugger/gdb_connection_manager.cpp',
            ],
            export_includes = [bld.repository_root.abspath(), os.path.join(bld.repository_root.abspath(), "libelf")],
            includes        = [bld.repository_root.abspath(), os.path.join(bld.repository_root.abspath(), "libelf")],
            use             = 'BOOST SYSTEMC TLM AMBA GREENSOCS ELF_LIB',
            install_path    = '${PREFIX}/lib',
        )

