#! /usr/bin/env python
# encoding: utf-8
#*********************************************************************
# Principal:  European Space Agency
# Author:     VLSI working group @ IDA @ TUBS
# Maintainer: Rolf Meyer
# Reviewed:
#*********************************************************************
top = '../..'

def build(bld):
  bld(
    target          = 'ahbprof',
    features        = 'cxx cxxstlib',
    source          = 'ahbprof.cpp', 
    export_includes = '.',
    uselib          = 'BOOST SYSTEMC TLM AMBA GREENSOCS',
    use             = 'utils signalkit common',
    install_path   = '${PREFIX}/lib',
  )
