#! /usr/bin/env python
# vim : set fileencoding=utf-8 expandtab noai ts=4 sw=4 filetype=python :
top = '../..'

def build(bld):
  import os.path
  bld(
    target          = 'memory',
    features        = 'cxx cxxstlib',
    source          = 'mapmemory.cpp arraymemory.cpp arraystorage.cpp mapstorage.cpp basememory.cpp memory.cpp memorypower.cpp', 
    export_includes = '.',
    uselib          = 'BOOST_PROGRAM_OPTIONS SYSTEMC TLM GREENSOCS',
    use             = 'utils signalkit common',
    install_path   = '${PREFIX}/lib',
  )
