#! /usr/bin/env python
# vim : set fileencoding=utf-8 expandtab noai ts=4 sw=4 filetype=python :
top = '../..'

def build(self):
    self(
        target          = 'gptimer',
        features        = 'cxx cxxstlib',
        source          = 'gptimer.cpp gpcounter.cpp', 
        export_includes = self.top_dir,
        includes = self.top_dir,
        uselib          = 'BOOST SYSTEMC TLM AMBA GREENSOCS',
        use             = 'common signalkit ',
        install_path   = '${PREFIX}/lib',
    )
