#!/usr/bin/env bash

if [ $# -lt 3 ] ; then
  echo "Usage: $0 <platform-name> <rom-name> <sdram-elf-name> [platform-arguments ...]"
  exit 1
fi

toolsdir=$(dirname $0)
topdir=$(dirname $(dirname ${toolsdir}))

lockfile=${topdir}/.lock-waf_linux2_build
if [ ! -f ${lockfile} ] ; then
    echo "Please run './waf configure && ./waf build' before you try to execute a platform!"
    exit 1
fi

builddir=$(${toolsdir}/get_python_attr ${topdir}/.lock-waf_linux2_build out_dir)

template=$1
prom=$2
app=$3
shift
shift
shift

platform=$(find ${builddir} -name "$template.platform")
prom=$(find ${builddir} -name "$prom.prom")
ram=$(find ${builddir} -name "$app.sparc")

echo $platform --loadelf \"rom=$prom\" --loadelf "\"sdram=$ram(0x40000000)\"" --intrinsics "\"leon3_0=$ram(standard)\"" $@
time $platform --loadelf "rom=$prom" --loadelf "sdram=$ram(0x40000000)" --intrinsics "leon3_0=$ram(standard)" $@
if [ $? -eq 0 ] ; then
  echo "!!! Successfull"
else
  echo "!!! Failed! Try:"
  echo gdb -ex run -ex bt --args $platform --loadelf \"rom=$prom\" --loadelf "\"sdram=$ram(0x40000000)\"" --intrinsics "\"leon3_0=$ram(standard)\"" $@
fi
