#!/usr/bin/env python2
import sys
from jsontools import get_json_attr

if __name__ == "__main__":
  if len(sys.argv)<2:
    sys.exit("Usage: get_json_attr <jsonfile> [dot.seperated.json.path]")
  else:
    attrname = None
    if len(sys.argv)>2:
      attrname = sys.argv[2]
    print get_json_attr(sys.argv[1], attrname)
    sys.exit(0)
