#! /usr/bin/env python
# encoding: utf-8
#***********************************************************************#
#* Project:    HW-SW SystemC Co-Simulation SoC Validation Platform     *#
#*                                                                     *#
#* File:       wscript                                                 *#
#*             this file contains the build system for the gptimer     *#
#*             tLM model and all its testbenches.                      *#
#*                                                                     *#
#* Modified on $Date: 2010-07-30 15:41:55 +0200 (Fri, 30 Jul 2010) $   *#
#*          at $Revision: 32 $                                         *#
#*                                                                     *#
#* Principal:  European Space Agency                                   *#
#* Author:     VLSI working group @ IDA @ TUBS                         *#
#* Maintainer: Rolf Meyer                                              *#
#***********************************************************************#

top = '..'

def set_options(ctx):
  from os import environ
  ctx.add_option("--DEBUGLEVEL", dest="debug", help="Defines the Debuglevel for the build", default=environ.get("DEBUG_LEVEL",""))

def configure(ctx):
  from Options import options
  import os.path
  if options.debug and options.debug != "":
    ctx.env["CXXFLAGS"] += ['-DDEBUG=%s' % (options.debug)]

def build(bld):
  bld(
    target         = 'outkit',
    features       = 'cxx cstaticlib',
    source         = 'verbose.cpp', 
    export_incdirs = '.',
    uselib         = 'SYSC'
  )
