#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os

def build(bld):
    bld.objects(
        target = 'elfloader',
        source = 'elf_frontend.cpp exec_loader.cpp',
        includes = '. ../..',
        use = 'ELF_LIB BOOST BOOST_FILESYSTEM',
        install_path = None
    )

    bld.install_files(os.path.join(bld.env.PREFIX, 'include', 'trap', 'elfloader'), 'elf_frontend.hpp exec_loader.hpp')
