#! /usr/bin/env python
# encoding: utf-8
#***********************************************************************#
#* Project:    HW-SW SystemC Co-Simulation SoC Validation Platform     *#
#*                                                                     *#
#* File:       wscript                                                 *#
#*             this file contains the build system for the gptimer     *#
#*             tLM model and all its testbenches.                      *#
#*                                                                     *#
#* Modified on $Date$   *#
#*          at $Revision$                                         *#
#*                                                                     *#
#* Principal:  European Space Agency                                   *#
#* Author:     VLSI working group @ IDA @ TUBS                         *#
#* Maintainer: Rolf Meyer                                              *#
#***********************************************************************#

top = '../..'

def set_options(ctx):
  pass 

def configure(ctx):
  pass

def build(bld):
  #bld(
  #  features = ['cxx', 'cprogram'],
  #  source='tests/top_tlm.cpp',
  #  target='gptimer.test',
  #  includes='. ../utils',
  #  uselib=['BOOST', 'SYSC', 'TLM2', 'AMBA', 'GREENSOCS'],
  #)
  
  bld(
    target       = 'speed.test',
    features     = 'cxx cprogram test',
    source       = 'tests/top_tlm.cpp',
    defines      = 'SPEEDTEST',
    includes     = '.',
    uselib       = 'BOOST SYSC TLM2 AMBA GREENSOCS',
    uselib_local = 'utils signalkit',
  )
  
  bld(
    target       = 'function.test',
    features     = 'cxx cprogram test',
    source       = 'tests/top_tlm.cpp',
    defines      = 'FUNCTIONTEST SCVAL=100 T1VAL=100 T2VAL=1000 TVAL3=10000 TVAL4=100 TESTLENGTH=1 DEBUGOUT=1',
    includes     = '.',
    uselib       = 'BOOST SYSC TLM2 AMBA GREENSOCS',
    uselib_local = 'utils signalkit',
  )

