#! /usr/bin/env python
# encoding: utf-8
#***********************************************************************#
#* Project:    HW-SW SystemC Co-Simulation SoC Validation Platform     *#
#*                                                                     *#
#* File:       wscript                                                 *#
#*             this file contains the build system for the gptimer     *#
#*             tLM model and all its testbenches.                      *#
#*                                                                     *#
#* Modified on $Date$   *#
#*          at $Revision$                                         *#
#*                                                                     *#
#* Principal:  European Space Agency                                   *#
#* Author:     VLSI working group @ IDA @ TUBS                         *#
#* Maintainer: Rolf Meyer                                              *#
#***********************************************************************#

top = '../..'

def set_options(ctx):
  pass 

def configure(ctx):
  pass

def build(bld):
  bld(
    target         = 'gptimer',
    features       = 'cxx cstaticlib',
    source         = 'gptimer.cpp gpcounter.cpp', 
    export_incdirs = '.',
    uselib         = 'SYSC TLM2 AMBA GREENSOCS',
    uselib_local   = 'utils signalkit common'
  )
  #bld(
  #  target       = 'speed.gptimer',
  #  features     = 'cxx cprogram test',
  #  source       = 'tests/top_tlm.cpp',
  #  defines      = 'SPEEDTEST',
  #  includes     = '. tests',
  #  uselib       = 'BOOST SYSC TLM2 AMBA GREENSOCS',
  #  uselib_local = 'utils signalkit',
  #)
  
  #bld(
  #  target       = 'function.gptimer',
  #  features     = 'cxx cprogram test',
  #  source       = 'tests/top_tlm.cpp',
  #  defines      = 'FUNCTIONTEST SCVAL=10 T1VAL=6 T2VAL=3 TVAL3=2 TVAL4=8 TESTLENGTH=1 DEBUGOUT=1',
  #  includes     = '. tests',
  #  uselib       = 'BOOST SYSC TLM2 AMBA GREENSOCS',
  #  uselib_local = 'utils signalkit',
  #)

  bld(
    target       = 'prescaler.gptimer',
    features     = 'cxx cprogram test',
    source       = 'tests/top_tlm.cpp',
    defines      = 'PRESCALERTEST CTBUS DEBUGOUT',
    includes     = '. tests',
    uselib       = 'BOOST SYSC TLM2 AMBA GREENSOCS',
    uselib_local = 'gptimer utils signalkit common',
  )

  bld(
    target       = 'counter.gptimer',
    features     = 'cxx cprogram test',
    source       = 'tests/top_tlm.cpp',
    defines      = 'COUNTERTEST CTBUS DEBUGOUT',
    includes     = '. tests',
    uselib       = 'BOOST SYSC TLM2 AMBA GREENSOCS',
    uselib_local = 'gptimer utils signalkit common',
  )

