#! /usr/bin/env python
# vim : set fileencoding=utf-8 expandtab noai ts=4 sw=4 filetype=python :
top = '..'

def build(bld):
  bld(
    target          = 'common',
    features        = 'cxx cxxstlib pyembed',
    source          = ['verbose.cpp',
                       'powermonitor.cpp',
                       'timingmonitor.cpp',
                       'msclogger.cpp',
                       'json_parser.cpp',
                       'block_allocator.cpp',
                       'paramprinter.cpp',
                       'shell.cpp'],
    export_includes = '.',
    includes        = '.',
    uselib          = 'GREENSOCS SYSTEMC TLM BOOST',
    use             = 'CULT OTF',
    install_path    = '${PREFIX}/lib',
  )

  bld(
    target          = 'simple.common',
    features        = 'cxx cprogram test',
    source          = 'tests/simple.cpp',
    includes        = '. CULT',
    uselib          = 'SYSTEMC',
    use             = 'common BOOST',
    install_path    = None,
  )

  bld(
    target          = 'gs_config_test',
    features        = 'cxx cprogram test',
    source          = 'tests/gs_config_test.cpp',
    includes        = 'GREENSOCS',
    uselib          = 'GREENSOCS SYSTEMC BOOST',
    use             = 'common BOOST',
    install_path    = None,
  )
 
