#! /usr/bin/env python
# vim : set fileencoding=utf-8 expandtab noai ts=4 sw=4 filetype=python :
top = '..'

def build(self):
  self(
    target          = 'common',
    features        = 'cxx cxxstlib pyembed',
    source          = ['verbose.cpp',
                       'powermonitor.cpp',
                       'timingmonitor.cpp',
                       'msclogger.cpp',
                       'json_parser.cpp',
                       'block_allocator.cpp',
                       'paramprinter.cpp',
                       'shell.cpp'],
    export_includes = self.top_dir,
    includes        = self.top_dir,
    uselib          = 'GREENSOCS SYSTEMC TLM BOOST',
    use             = 'CULT OTF',
    install_path    = '${PREFIX}/lib',
  )
