#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import os

def build(bld):

    bld.recurse('register')

    bld.install_files(os.path.join(bld.env.PREFIX, 'include', 'trap', 'modules'), 'abi_if.hpp instruction.hpp sparse_memory_at.hpp sparse_memory_lt.hpp memory_lt.hpp memory_at.hpp pin_target.hpp register.hpp')
