#! /usr/bin/env python
# vim : set fileencoding=utf-8 expandtab noai ts=4 sw=4 filetype=python :
top = '../..'

def build(self):

  self(
    target          = 'reset_irqmp',
    features        = 'cxx cxxstlib',
    source          = 'reset_irqmp.cpp',
    export_includes = self.top_dir,
    includes = self.top_dir,
    use             = 'common SYSTEMC TLM AMBA GREENSOCS',
    install_path    = '${PREFIX}/lib',
  )

