#! /usr/bin/env python
# vim : set fileencoding=utf-8 expandtab noai ts=4 sw=4 filetype=python :
top = '../../..'

def build(self):

    self(
        target          = 'mmucache',
        features        = 'cxx cxxstlib',
        source          = [ 
                            'mmucache/icio_payload_extension.cpp', 
                            'mmucache/dcio_payload_extension.cpp',
                            'mmucache/localram.cpp',
                            'mmucache/nocache.cpp',
                            'mmucache/vectorcache.cpp',
                            'mmucache/ivectorcache.cpp',
                            'mmucache/dvectorcache.cpp',
                            'mmucache/mmu.cpp', 
                            'mmucache/mmu_cache.cpp',
                            'mmucache/mmu_cache_base.cpp',
                            'mmucache/defines.cpp'
                          ],
        export_includes = self.top_dir,
        includes        = self.top_dir,
        use             = 'common sr_register',
        install_path    = '${PREFIX}/lib',
    )

    self(
        target          = 'leon3',
        features        = 'cxx cxxstlib',
        export_includes = self.top_dir,
        includes        = self.top_dir,
        use             = 'mmucache trap common',
        source          = [
                            'intunit/instructions.cpp',
                            'intunit/registers.cpp',
                            'intunit/alias.cpp',
                            'intunit/processor.cpp',
                            'intunit/interface.cpp',
                            'intunit/decoder.cpp',
                            'intunit/memory.cpp',
                            'intunit/irqPorts.cpp',
                            'intunit/externalPins.cpp',
                            'leon3.cpp',
                          ],
        install_path    = '${PREFIX}/lib',
        defines         = 'ENABLE_HISTORY', 
    )
