#! /usr/bin/env python
# encoding: utf-8
#*********************************************************************
# Copyright 2010, Institute of Computer and Network Engineering,
#                 TU-Braunschweig
# All rights reserved
# Any reproduction, use, distribution or disclosure of this program,
# without the express, prior written consent of the authors is
# strictly prohibited.
#
# University of Technology Braunschweig
# Institute of Computer and Network Engineering
# Hans-Sommer-Str. 66
# 38118 Braunschweig, Germany
#
# ESA SPECIAL LICENSE
#
# This program may be freely used, copied, modified, and redistributed
# by the European Space Agency for the Agency's own requirements.
#
# The program is provided "as is", there is no warranty that
# the program is correct or suitable for any purpose,
# neither implicit nor explicit. The program and the information in it
# contained do not necessarily reflect the policy of the European
# Space Agency or of TU-Braunschweig.
#*********************************************************************
# Title:      wscripto
#
# ScssId:
#
# Origin:     HW-SW SystemC Co-Simulation SoC Validation Platform
#
# Purpose:    The WAF-Script for building the AHBCTRL files and tests.
#
# Method:     $ ./waf configure; ./waf # to build it on top level
#
# Modified on $Date: 2010-10-07 19:02:15 +0200 (Thu, 07 Oct 2010) $
#          at $Revision: 165 $
#          by $Author: HWSWSIM $
#
# Principal:  European Space Agency
# Author:     VLSI working group @ IDA @ TUBS
# Maintainer: Rolf Meyer
# Reviewed:
#*********************************************************************
top = '../..'
vsim_conf = """
[Library]
modelsim = $GRLIB_TECH
grlib = $GRLIB_TECH/grlib
unisim = $GRLIB_TECH/unisim
dw02 = $GRLIB_TECH/dw02
synplify = $GRLIB_TECH/synplify
techmap = $GRLIB_TECH/techmap
spw = $GRLIB_TECH/spw
eth = $GRLIB_TECH/eth
opencores = $GRLIB_TECH/opencores
gaisler = $GRLIB_TECH/gaisler
esa = $GRLIB_TECH/esa
micron = $GRLIB_TECH/micron
vsys = $GRLIB_TECH/vsys
std = $MODEL_TECH/../std
ieee = $MODEL_TECH/../ieee
vital2000 = $MODEL_TECH/../vital2000
verilog = $MODEL_TECH/../verilog
std_developerskit = $MODEL_TECH/../std_developerskit
synopsys = $MODEL_TECH/../synopsys
work = %(path)s/%(target)s

[vcom]
VHDL93 = 1
Show_source = 1
Show_Warning1 = 0
Show_Warning5 = 0
Quiet = 1

[vlog]
Quiet = 1

[vsim]
VoptFlow = 0
Resolution = 1ps
UserTimeUnit = ns
RunLength = 100
IterationLimit = 5000
BreakOnAssertion = 3
DefaultRadix = symbolic
TranscriptFile = transcript.txt
PathSeparator = /
UnbufferedOutput = 0

[lmc]
libsm = $MODEL_TECH/libsm.sl
libhm = $MODEL_TECH/libhm.sl
"""

def build(bld):
  bld(
    target         = 'ahbctrl',
    features       = 'cxx cxxstlib',
    source         = ['ahbctrl.cpp'],
    export_includes = '.',
    includes       = '.',
    uselib         = 'SYSTEMC TLM AMBA GREENSOCS',
    use            = 'utils common'
  )

  bld(
    target         = 'ahbctrl_test',
    features       = 'cxx cxxstlib',
    source         = ['tests/ahbctrl_test.cpp'],
    export_includes = 'tests',
    includes       = 'tests',
    uselib         = 'SYSTEMC TLM AMBA GREENSOCS',
    use            = 'utils common'
  )

  bld(
    target         = 'ahbctrl.1.lt.test',
    features       = 'cxx cprogram test',
    source         = ['tests/test1/testbench.cpp',
                      'tests/test1/top_lt.cpp'],
    includes       = '. adapters tests tests/test1',
    uselib         = 'SYSTEMC TLM AMBA GREENSOCS',
    use            = 'common utils ahbctrl ahbctrl_tests ahbmem',
  )
 
  bld(
    target         = 'ahbctrl.1.at.test',
    features       = 'cxx cprogram test',
    source         = ['tests/test1/testbench.cpp',
                      'tests/test1/top_at.cpp'],
    includes       = '. tests tests/test1',
    uselib         = 'SYSTEMC TLM AMBA GREENSOCS',
    use            = 'common utils ahbctrl ahbctrl_test ahbmem',
  )

  bld(
    features       = 'modelsim',
    target         = 'ahbctrl.1.rtl.test',
    name           = 'ahbctrl.1.rtl.test',
    source         = ['tests/typ_adapters.vhd',
                      'tests/test1/ahbctrl_wrapper.vhd',
                      'tests/ahbctrl_test.cpp',
                      'tests/test1/testbench.cpp',
                      'tests/test1/top_rtl.cpp',
                      '../../common/verbose.cpp',
                      '../../common/timingmonitor.cpp',
                      '../utils/ahbdevice.cpp',
                      '../ahbmem/ahbmem.cpp',
                      '../utils/clock_gen.cpp',
                      '../../adapters/ahbpipe.cpp',
                      '../../adapters/ahb_tlmmaster_rtlbus_transactor.cpp',
                      '../../adapters/ahb_rtlbus_tlmslave_transactor.cpp'],
    uselib         = 'AMBA GREENSOCS',
    vcomflags      = '-93 -explicit',
    includes       = '. tests tests/test1 ../../adapters ../../common ../../signalkit ../utils ../ahbmem',
    config         =  vsim_conf,
  )
  
  bld(
    target         = 'ahbctrl.2.lt.test',
    features       = 'cxx cprogram test',
    source         = ['tests/ahbctrl_test.cpp',
                      'tests/test2/testbench.cpp',
                      'tests/test2/top_lt.cpp'],
    includes       = '. adapters tests tests/test2',
    uselib         = 'SYSTEMC TLM AMBA GREENSOCS',
    use            = 'common utils ahbctrl ahbmem',
  )
 
  bld(
    target         = 'ahbctrl.2.at.test',
    features       = 'cxx cprogram test',
    source         = ['tests/ahbctrl_test.cpp',
                      'tests/test2/testbench.cpp',
                      'tests/test2/top_at.cpp'],
    includes       = '. adapters tests tests/test2',
    uselib         = 'SYSTEMC TLM AMBA GREENSOCS',
    use            = 'common utils ahbctrl ahbmem',
  )

  bld(
    features       = 'modelsim',
    target         = 'ahbctrl.2.rtl.test',
    name           = 'ahbctrl.2.rtl.test',
    source         = ['tests/typ_adapters.vhd',
                      'tests/test2/ahbctrl_wrapper.vhd',
                      'tests/ahbctrl_test.cpp',
                      'tests/test2/testbench.cpp',
                      'tests/test2/top_rtl.cpp',
                      '../../common/verbose.cpp',
                      '../../common/timingmonitor.cpp',
                      '../utils/ahbdevice.cpp',
                      '../ahbmem/ahbmem.cpp',
                      '../utils/clock_gen.cpp',
                      '../../adapters/ahbpipe.cpp',
                      '../../adapters/ahb_tlmmaster_rtlbus_transactor.cpp',
                      '../../adapters/ahb_rtlbus_tlmslave_transactor.cpp'],
    uselib         = 'AMBA GREENSOCS',
    vcomflags      = '-93 -explicit',
    includes       = '. tests tests/test2 ../../adapters ../../common ../../signalkit ../utils ../ahbmem',
    config         =  vsim_conf,
  )

  bld(
    target         = 'ahbctrl.3.lt.test',
    features       = 'cxx cprogram test',
    source         = ['tests/ahbctrl_test.cpp',
                      'tests/test3/testbench.cpp',
                      'tests/test3/top_lt.cpp'],
    includes       = '. adapters tests tests/test3',
    uselib         = 'SYSTEMC TLM AMBA GREENSOCS',
    use            = 'common utils ahbctrl ahbmem',
  )
 
  bld(
    target         = 'ahbctrl.3.at.test',
    features       = 'cxx cprogram test',
    source         = ['tests/ahbctrl_test.cpp',
                      'tests/test3/testbench.cpp',
                      'tests/test3/top_at.cpp'],
    includes       = '. adapters tests tests/test3',
    uselib         = 'SYSTEMC TLM AMBA GREENSOCS',
    use            = 'common utils ahbctrl ahbmem',
  )

  bld(
    features       = 'modelsim',
    target         = 'ahbctrl.3.rtl.test',
    name           = 'ahbctrl.3.rtl.test',
    source         = ['tests/typ_adapters.vhd',
                      'tests/test3/ahbctrl_wrapper.vhd',
                      'tests/ahbctrl_test.cpp',
                      'tests/test3/testbench.cpp',
                      'tests/test3/top_rtl.cpp',
                      '../../common/verbose.cpp',
                      '../../common/timingmonitor.cpp',
                      '../utils/ahbdevice.cpp',
                      '../ahbmem/ahbmem.cpp',
                      '../utils/clock_gen.cpp',
                      '../../adapters/ahbpipe.cpp',
                      '../../adapters/ahb_tlmmaster_rtlbus_transactor.cpp',
                      '../../adapters/ahb_rtlbus_tlmslave_transactor.cpp'],
    uselib         = 'AMBA GREENSOCS',
    vcomflags      = '-93 -explicit',
    includes       = '. tests tests/test3 ../../adapters ../../common ../../signalkit ../utils ../ahbmem',
    config         =  vsim_conf,
  )

  bld(
    target         = 'ahbctrl.4.lt.test',
    features       = 'cxx cprogram test',
    source         = ['tests/ahbctrl_test.cpp',
                      'tests/test4/testbench.cpp',
                      'tests/test4/top_lt.cpp'],
    includes       = '. adapters tests tests/test4',
    uselib         = 'SYSTEMC TLM AMBA GREENSOCS',
    use            = 'common utils ahbctrl ahbmem',
  )
 
  bld(
    target         = 'ahbctrl.4.at.test',
    features       = 'cxx cprogram test',
    source         = ['tests/ahbctrl_test.cpp',
                      'tests/test4/testbench.cpp',
                      'tests/test4/top_at.cpp'],
    includes       = '. adapters tests tests/test4',
    uselib         = 'SYSTEMC TLM AMBA GREENSOCS',
    use            = 'common utils ahbctrl ahbmem',
  )

  bld(
    features       = 'modelsim',
    target         = 'ahbctrl.4.rtl.test',
    name           = 'ahbctrl.4.rtl.test',
    source         = ['tests/typ_adapters.vhd',
                      'tests/test4/ahbctrl_wrapper.vhd',
                      'tests/ahbctrl_test.cpp',
                      'tests/test4/testbench.cpp',
                      'tests/test4/top_rtl.cpp',
                      '../../common/verbose.cpp',
                      '../../common/timingmonitor.cpp',
                      '../utils/ahbdevice.cpp',
                      '../ahbmem/ahbmem.cpp',
                      '../utils/clock_gen.cpp',
                      '../../adapters/ahbpipe.cpp',
                      '../../adapters/ahb_tlmmaster_rtlbus_transactor.cpp',
                      '../../adapters/ahb_rtlbus_tlmslave_transactor.cpp'],
    uselib         = 'AMBA GREENSOCS',
    vcomflags      = '-93 -explicit',
    includes       = '. tests tests/test4 ../../adapters ../../common ../../signalkit ../utils ../ahbmem',
    config         =  vsim_conf,
  )

  bld(
    target         = 'ahbctrl.5.lt.test',
    features       = 'cxx cprogram test',
    source         = ['tests/ahbctrl_test.cpp',
                      'tests/test5/testbench.cpp',
                      'tests/test5/top_lt.cpp'],
    includes       = '. adapters tests tests/test5',
    uselib         = 'SYSTEMC TLM AMBA GREENSOCS',
    use            = 'common utils ahbctrl ahbmem',
  )
 
  bld(
    target         = 'ahbctrl.5.at.test',
    features       = 'cxx cprogram test',
    source         = ['tests/ahbctrl_test.cpp',
                      'tests/test5/testbench.cpp',
                      'tests/test5/top_at.cpp'],
    includes       = '. adapters tests tests/test5',
    uselib         = 'SYSTEMC TLM AMBA GREENSOCS',
    use            = 'common utils ahbctrl ahbmem',
  )

  bld(
    features       = 'modelsim',
    target         = 'ahbctrl.5.rtl.test',
    name           = 'ahbctrl.5.rtl.test',
    source         = ['tests/typ_adapters.vhd',
                      'tests/test5/ahbctrl_wrapper.vhd',
                      'tests/ahbctrl_test.cpp',
                      'tests/test5/testbench.cpp',
                      'tests/test5/top_rtl.cpp',
                      '../../common/verbose.cpp',
                      '../../common/timingmonitor.cpp',
                      '../utils/ahbdevice.cpp',
                      '../ahbmem/ahbmem.cpp',
                      '../utils/clock_gen.cpp',
                      '../../adapters/ahbpipe.cpp',
                      '../../adapters/ahb_tlmmaster_rtlbus_transactor.cpp',
                      '../../adapters/ahb_rtlbus_tlmslave_transactor.cpp'],
    uselib         = 'AMBA GREENSOCS',
    vcomflags      = '-93 -explicit',
    includes       = '. tests tests/test5 ../../adapters ../../common ../../signalkit ../utils ../ahbmem',
    config         =  vsim_conf,
  )


