#!/usr/bin/env bash

if [ $# -lt 3 ] ; then
  echo "Usage: $0 <platform-name> <rom-name> <sdram-elf-name> [platform-arguments ...]"
  exit 1
fi

toolsdir=$(dirname $0)
topdir=$(dirname ${toolsdir})

lockfile=${topdir}/.lock-waf_linux2_build
if [ ! -f ${lockfile} ] ; then
    echo "Please run './waf configure && ./waf build' before you try to execute a platform!"
    exit 1
fi

builddir=$(${toolsdir}/get_python_attr ${topdir}/.lock-waf_linux2_build out_dir)

template=$1
prom=$2
app=$3
shift
shift
shift

ppath="${builddir}/platforms/$template"
platform="$ppath/$template.platform"
prom="${builddir}/software/prom/$prom/$prom.prom"
ram=$(find ${builddir}/software -name "$app.sparc")

echo $platform --option conf.mctrl.prom.elf=$prom --option conf.mctrl.ram.sdram.elf=$ram --option conf.system.osemu=$ram $@
time $platform --option conf.mctrl.prom.elf=$prom --option conf.mctrl.ram.sdram.elf=$ram --option conf.system.osemu=$ram $@
if [ $? -eq 0 ] ; then
  echo "!!! Successfull"
else
  echo "!!! Failed"
fi
