#!/usr/bin/env bash

if [ $# -lt 3 ] ; then
  echo "Usage: $0 <platform-name> <rom-name> <sdram-elf-name> [platform-arguments ...]"
  exit 1
fi

template=$1
prom=$2
app=$3
shift
shift
shift

ppath="build/platforms/$template/"
platform="$ppath/$template.platform"
prom="build/software/prom/$prom/$prom.prom"
ram=$(find build/software -name "$app.sparc")

$platform --option conf.mctrl.prom.elf=$prom --option conf.mctrl.ram.sdram.elf=$ram --option conf.system.osemu=$ram $@
if [ $? -ne 0 ] ; then
  echo "!!! Successfull"
else
  echo "!!! Failed"
fi
