#!/usr/bin/env python2
import sys
from pythontools import get_python_attr

if __name__ == "__main__":
  if len(sys.argv)<2:
    sys.exit("Usage: get_python_attr <pythonfile> [dot.seperated.json.path]")
  else:
    attrname = None
    if len(sys.argv)>2:
      attrname = sys.argv[2]
    print get_python_attr(sys.argv[1], attrname)
    sys.exit(0)
