#!/usr/bin/env python
import json
import sys
if len(sys.argv)<2:
  print "Usage: get_json_attr <jsonfile> [dot.seperated.json.path]"
  sys.exit(1)
else:
  filename = sys.argv[1].strip('"').strip("'")
  filehandler = open(filename)
  obj = json.load(filehandler)
  if len(sys.argv)>2:
    for idx in sys.argv[2].split('.') or []:
      obj = obj[idx]
  print obj
  sys.exit(0)
