#!/usr/bin/env python
# -*- coding: utf-8 -*-

from argparse import ArgumentParser
import argparse
from collections import deque
import collections

parser = ArgumentParser(description="%(prog)s - A Tool to print selected lines from a LOGFILE to standard output.")
parser.add_argument("-f", "--file",
	dest="logfile",
	required=True,
	help="logfilename",
)
parser.add_argument("-s", "--starttime",
	dest="starttime",
	required=True,
	type=int,
	help="starttime",
)
parser.add_argument("-e","--endtime",
	dest="endtime",
	type=int,
	help="endtime"
)
parser.add_argument("-pre", "--prelines",
	dest="prelines",
	type=int,
	help="prelines",
)
parser.add_argument("-post", "--postlines",
	dest="postlines",
	type=int,
	default=0,
	help="postlines",
)
parser.add_argument("-sep", "--seperator",
	dest="sep",
	default=" ",
	help="seperator",
)
parser.add_argument("--version",
	action='version',
	version='%(prog)s 0.2',
	help="print %(prog)s version and exit"
)
args = parser.parse_args()

postlines = args.postlines
printpostlines = True
endtime = (args.starttime if (args.endtime is None) else args.endtime)

prelinebuffer = collections.deque(maxlen=(args.prelines if args.prelines > 0 else 0))

with open(args.logfile, "r") as logfile:
	for rawline in logfile:
		line = rawline.replace('\n', '')
		logtime = int(line.split(args.sep)[0])

		if (logtime < args.starttime):
			prelinebuffer.append(line)
			printpostlines = (True if (postlines > 0) else False)
			continue
		else:
			if (len(prelinebuffer) > 0):
				for preline in prelinebuffer:
					print(preline)
				prelinebuffer.clear()
			if (logtime <= endtime or printpostlines):
				print(line)
			if (logtime > endtime and printpostlines):
				postlines -= 1
				if (postlines <= 0):
					printpostlines = False
					postlines = args.postlines
