#!/usr/bin/env python
import json
import sys
if len(sys.argv)<3:
  print "Usage: get_json_attr <jsonfile> dot.seperated.json.path=value [...]"
  sys.exit(1)
else:
  filename = sys.argv[1].strip('"').strip("'")
  filehandler = open(filename)
  root = json.load(filehandler)
  for param in sys.argv[2:]:
    obj = root
    pair = param.split('=')
    if len(pair) != 2:
      print "Parameter %s is wrong please use 'key=value' as pattern" % (param)
      sys.exit(1)
    if pair[1].isdigit():
      pair[1] = int(pair[1])
    elif pair[1] == "true":
      pair[1] = True
    elif pair[1] == "false":
      pair[1] = False

    else:
      path = pair[0].split('.') or []
      for idx in path:
        if obj.has_key(idx):
          if idx != path[-1]:
            obj = obj[idx]
          else:
            obj[idx] = pair[1]
        else:
          if idx != path[-1]:
            obj[idx] = {}
            obj = obj[idx]
          else:
            obj[idx] = pair[1]

  print json.dumps(root, sort_keys=True, indent=2)
  sys.exit(0)
