#!/usr/bin/env python2
import sys
from jsontools import set_json_attr

if __name__ == "__main__":
  if len(sys.argv)<3:
    sys.exit("Usage: get_json_attr <jsonfile> dot.seperated.json.path=value [...]")
  else:
    print set_json_attr(sys.argv[1], sys.argv[2:])
    sys.exit(0)
