#!/bin/bash

./waf list | grep $1.$2.lt.test && ./waf --target=$1.$2.lt.test
./waf list | grep $1.$2.at.test && ./waf --target=$1.$2.at.test
./waf list | grep $1.$2.rtl.test && ./waf --target=$1.$2.rtl.test

./waftools/timingreport $1 $2

cat build/timingreports/$1.$2.report.csv;
