#! /usr/bin/env python
# vim : set fileencoding=utf-8 expandtab noai ts=4 sw=4 filetype=python :
top = '../..'

def build(bld):
  bld(
    target         = 'ahbctrl',
    features       = 'cxx cxxstlib',
    source         = ['ahbctrl.cpp'],
    export_includes = '.',
    includes       = '.',
    use            = 'common SYSTEMC TLM AMBA GREENSOCS',
    install_path   = '${PREFIX}/lib',
  )
