#! /usr/bin/env python
# vim : set fileencoding=utf-8 expandtab noai ts=4 sw=4 filetype=python :
top = '../..'

def build(bld):
  bld(
    target          = 'apbuart',
    features        = 'cxx cxxstlib',
    source          = 'apbuart.cpp tcpio.cpp nullio.cpp', 
    export_includes = '.',
    uselib          = 'BOOST SYSTEMC TLM AMBA GREENSOCS',
    use             = 'common signalkit utils',
    install_path    = '${PREFIX}/lib',
  )
