#! /usr/bin/env python
# encoding: utf-8
#***********************************************************************#
#* Project:    HW-SW SystemC Co-Simulation SoC Validation Platform     *#
#*                                                                     *#
#* File:       wscript                                                 *#
#*             this file contains the build system for the gptimer     *#
#*             tLM model and all its testbenches.                      *#
#*                                                                     *#
#* Modified on $Date$   *#
#*          at $Revision$                                         *#
#*                                                                     *#
#* Principal:  European Space Agency                                   *#
#* Author:     VLSI working group @ IDA @ TUBS                         *#
#* Maintainer: Rolf Meyer                                              *#
#***********************************************************************#

top = '..'

def set_options(ctx): 
  pass

def configure(ctx):
  pass

def build(bld):
  bld(
    target         = 'utils',
    features       = 'cxx cstaticlib',
    source         = [#'ahb_rtl_ct.cpp',
                      #'apb_ct_rtl.cpp',
                      'tb_ahb_mem.cpp', 
                      'grlibdevice.cpp',
                      'apbtestbench.cpp',
                     ],
    export_incdirs = '.',
    uselib         = 'SYSC TLM2 AMBA GREENSOCS',
    uselib_local   = 'signalkit vkit'
  )
