#! /usr/bin/env python
# vim : set fileencoding=utf-8 expandtab noai ts=4 sw=4 filetype=python :
top = '../..'

def build(self):
  self(
    target          = 'utils',
    features        = 'cxx cxxstlib',
    source          = [
                       'memdevice.cpp',
                       'clkdevice.cpp',
                      ],
    export_includes = self.top_dir,
    includes        = self.top_dir,
    uselib          = 'SYSTEMC TLM AMBA GREENSOCS',
    use             = 'signalkit common',
    install_path    = '${PREFIX}/lib',
  )
