#! /usr/bin/env python
# encoding: utf-8
#*********************************************************************
# Copyright 2010, Institute of Computer and Network Engineering,
#                 TU-Braunschweig
# All rights reserved
# Any reproduction, use, distribution or disclosure of this program,
# without the express, prior written consent of the authors is 
# strictly prohibited.
#
# University of Technology Braunschweig
# Institute of Computer and Network Engineering
# Hans-Sommer-Str. 66
# 38118 Braunschweig, Germany
#
# ESA SPECIAL LICENSE
#
# This program may be freely used, copied, modified, and redistributed
# by the European Space Agency for the Agency's own requirements.
#
# The program is provided "as is", there is no warranty that
# the program is correct or suitable for any purpose,
# neither implicit nor explicit. The program and the information in it
# contained do not necessarily reflect the policy of the European 
# Space Agency or of TU-Braunschweig.
#*********************************************************************
# Title:      wscript
#
# ScssId:
#
# Origin:     HW-SW SystemC Co-Simulation SoC Validation Platform
#
# Purpose:    this file contains the build system for utils
#             needed by the tlm models or their testbenches
#
# Method:     $ ./waf configure; ./waf # to build it on top level
#
# Modified on $Date$
#          at $Revision$
#          by $Author$
#
# Principal:  European Space Agency
# Author:     VLSI working group @ IDA @ TUBS
# Maintainer: Rolf Meyer
# Reviewed:
#*********************************************************************
top = '..'

def options(ctx): 
  pass

def configure(ctx):
  pass

def build(bld):
  bld(
    target          = 'utils',
    features        = 'cxx cxxstlib',
    source          = [#'ahb_rtl_ct.cpp',
                       #'apb_ct_rtl.cpp',
                       'tb_ahb_mem.cpp', 
                       'ahbdevice.cpp',
                       'apbdevice.cpp',
                       'apbtestbench.cpp',
                      ],
    export_includes = '.',
    uselib          = 'SYSTEMC TLM AMBA GREENSOCS',
    use             = 'signalkit common'
  )
