#! /usr/bin/env python
# encoding: utf-8
#***********************************************************************#
#* Project:    HW-SW SystemC Co-Simulation SoC Validation Platform     *#
#*                                                                     *#
#* File:       wscript                                                 *#
#*             this file contains the build system for the gptimer     *#
#*             tLM model and all its testbenches.                      *#
#*                                                                     *#
#* Modified on $Date$   *#
#*          at $Revision$                                         *#
#*                                                                     *#
#* Principal:  European Space Agency                                   *#
#* Author:     VLSI working group @ IDA @ TUBS                         *#
#* Maintainer: Rolf Meyer                                              *#
#***********************************************************************#

top = '../..'

def set_options(ctx): 
  pass

def configure(ctx):
  pass

def build(bld):
  bld(
    target         = 'irqmp',
    features       = 'cxx cstaticlib',
    source         = 'irqmp.cpp', 
    export_incdirs = '.',
    uselib         = 'SYSC TLM2 AMBA GREENSOCS',
    uselib_local   = 'utils signalkit vkit'
  )

  bld(
    features     = 'cxx cprogram test',
    source       = 'tests/top_tlm.cpp tests/testbench.cpp',
    target       = 'simple.irqmp',
    includes     = '.',
    uselib       = 'BOOST SYSC TLM2 AMBA GREENSOCS',
    uselib_local = 'irqmp utils signalkit vkit'
  )
  
