#! /usr/bin/env python
# encoding: utf-8
#***********************************************************************#
#* Project:    HW-SW SystemC Co-Simulation SoC Validation Platform     *#
#*                                                                     *#
#* File:       wscript                                                 *#
#*             this file contains the build system for the models      *#
#*             directory. It triggers the build of all models          *#
#*                                                                     *#
#* Modified on $Date$   *#
#*          at $Revision$                                         *#
#*                                                                     *#
#* Principal:  European Space Agency                                   *#
#* Author:     VLSI working group @ IDA @ TUBS                         *#
#* Maintainer: Rolf Meyer                                              *#
#***********************************************************************#

top = '..'

models = [
  'gptimer', 
  'irqmp', 
  'mmu_cache', 
  'mctrl', 
  'pnp',
  'utils',
  'socwire'
]

def set_options(ctx): 
  ctx.recurse(models)

def configure(ctx):
  ctx.recurse(models)

def build(bld):
  bld.add_subdirs(models)
